name: ovorideuser
description: OvoRide is a complete ride-sharing solution.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  another_flushbar: ^1.12.30
  awesome_dialog: ^3.2.1
  cached_network_image: ^3.4.1
  connectivity_plus: ^6.1.4
  coupon_uikit: ^0.2.1
  cupertino_icons: ^1.0.8
  dio: ^5.8.0+1
  dotted_border: ^3.1.0
  file_picker: ^10.2.0
  firebase_core: ^3.15.1
  firebase_messaging: ^15.2.9
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.2
  flutter_inappwebview: ^6.1.5
  flutter_local_notifications: ^19.3.0
  flutter_rating_bar: ^4.0.1
  flutter_spinkit: ^5.2.1
  flutter_svg: ^2.2.0
  flutter_widget_from_html: ^0.16.0
  geocoding: ^4.0.0
  geolocator: ^14.0.2
  get: ^4.7.2
  google_maps_flutter: ^2.12.3
  google_sign_in: ^7.1.0
  image_picker: ^1.1.2
  in_app_review: ^2.0.10
  intl: ^0.20.2
  just_audio: 0.10.4
  line_icons: ^2.0.3
  logger: ^2.6.0
  lottie: ^3.3.1
  open_file: ^3.5.10
  path_provider: ^2.1.5
  permission_handler: ^12.0.1
  pin_code_fields: ^8.0.1
  pusher_channels_flutter: ^2.5.0
  share_plus: ^11.0.0
  shared_preferences: ^2.5.3
  shimmer: ^3.0.0
  sign_in_with_apple: ^7.0.1
  timelines_plus: ^1.0.7
  timezone: ^0.10.1
  url_launcher: ^6.3.1
  vibration: ^3.1.3
  zoom_tap_animation: ^1.1.0

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

dependency_overrides:
  intl: any
  file_picker: any
  just_audio: any

flutter:
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/images/social/
    - assets/images/logo/
    - assets/images/onboard/
    - assets/icon/
    - assets/icon/files/
    - assets/img/
    - assets/img/icon/
    - assets/img/map/
    - assets/animation/
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Black.ttf
        - asset: assets/fonts/Inter-Bold.ttf
        - asset: assets/fonts/Inter-ExtraLight.ttf
        - asset: assets/fonts/Inter-Light.ttf
        - asset: assets/fonts/Inter-Medium.ttf
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-SemiBold.ttf
        - asset: assets/fonts/Inter-Thin.ttf
